# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np

In [44]:
onedim = np.arange(0,10)
onedim.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [6]:
array1 = np.arange(0,10).reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
array2 = np.ones(10).reshape(2,5)
array2.astype(np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [37]:
np.vstack((array1,array2))

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [49]:
hrarray = np.hstack((array1,array2))
hrarray.astype(np.int32)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [61]:
flatarray = np.arange(0,10).reshape(2,5)
flatarray

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [63]:
flatarray.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [22]:
higherdim = np.arange(15).reshape(3,5)
higherdim

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [24]:
higherdim.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [38]:
onedimen = np.arange(0,15)
onedimen

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
onedimen.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [43]:
squarearray = np.arange(25).reshape(5,5)
squarearray

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
squarearray**2

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [54]:
meanaray = np.arange(30).reshape(5,6)
meanaray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [59]:
res = np.mean(meanaray)
res

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [60]:
np.std(meanaray)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [61]:
np.median(meanaray)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [62]:
np.transpose(meanaray)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [65]:
diagonalsum = np.arange(16).reshape(4,4)
diagonalsum

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
np.trace(diagonalsum)

30

## Question:13

### Find the determinant of the previous array in Q12?

In [78]:
deter =  np.linalg.det(diagonalsum)
deter

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

In [82]:
perc = np.arange(20,40)
np.percentile(perc,5)

20.950000000000003

In [83]:
np.percentile(perc,95)

38.05

## Question:15

### How to find if a given array has any null values?

In [159]:
an_array = np.empty((3,3))

an_array[1] = np.NaN
an_array


array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [             nan,              nan,              nan],
       [ 1.33509015e-307, -1.73791455e-311,              nan]])